// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABGZ5wBsTXXDzRU8z4srCe3rb26GdgmcQ',
    appId: '1:355379148887:web:c95f6e40050bf56d19cb12',
    messagingSenderId: '355379148887',
    projectId: 'ds-repaserv',
    authDomain: 'ds-repaserv.firebaseapp.com',
    storageBucket: 'ds-repaserv.firebasestorage.app',
    measurementId: 'G-EG09FYCD2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIrvoYMRWjZzEo3nAsC9zhkLGrZk3MJU0',
    appId: '1:355379148887:android:3abaa2fa4e068fdd19cb12',
    messagingSenderId: '355379148887',
    projectId: 'ds-repaserv',
    storageBucket: 'ds-repaserv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_OvjRmvCgGPEW9fYU1_WSxHQ3dS7oHkA',
    appId: '1:355379148887:ios:089263431905edb319cb12',
    messagingSenderId: '355379148887',
    projectId: 'ds-repaserv',
    storageBucket: 'ds-repaserv.firebasestorage.app',
    iosBundleId: 'com.example.repaserv',
  );
}
